name: API Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3

      - name: Checking API for backward compatibility
        run: ./gradlew apiCheck
